### ISSUE TITLE
M3 requirements

### ISSUE THREAD

**Issue by vergenzt** [cs2340-group3/moviebuzz#1]
(Copied from T-square)
# M3 - Login / Logout and Use Cases
## Design
1. Create a Context Diagram for the system
2. ~~Brainstorm and list 10 use cases (title only) (See Chapter 6 of Book) You may have fewer than 10 use cases if you can cover the entire system in fewer. The fully detailed use cases should then show other extensions and alternatives within a higher level use case.~~
3. Each person on the team pick 1 use case and fully detail it (this is an individual grade, so you do not have to cover for a team mate)
## Implementation
1. ~~Create your team's Web Project and Import into Git~~
2. Create an opening or welcome screen which has options for Login and Registration. You may have some other method of differentiating login and registration.
3. If someone selects Login, then you should display a way to enter the user name and password.
4. If someone requests login, you should check for the correct user name and password. For this first milestone, you should have a hard coded user with name "user" and password "pass" to check against.
5. If the login matches user name / password then go to your application. Otherwise, notify of the bad login attempt.
6. Canceling the login (press Cancel for example) will close out the login attempt , but no information is recorded and the application does not start up. Note here you are not explicitly required to have a cancel button, just a way to back out of the login.
7. Once in the application, there should be a way to logout. After logging out, the application should return to the welcome page.
### Team Points - 55
1. Context diagram covers all actors (5)
2. 10 use cases (or fewer, see above) are listed. They are appropriate and phrased as verb-direct object ..... (10)
3. Web project is created and launches .... (5)
4. Welcome screen displays (or alternative).... (5)
5. Welcome screen (or alternative) has controls for login or registration .... (5)
6. Selecting login brings up screen to enter information .... (5)
7. Screen displays fields for inputting user name and password .... (5)
8. Login/Cancel(abort login) has appropriate action (10)
9. Logout functions correctly (5)
### Individual Points - 45

Use case selected has the following features:
- Primary Actor appropriate and identified ..... (2)
- Other stakeholders and their goals ..... (3)
- Preconditions (what has to be true/what other use cases completed before this use case can execute) ..... (5)
- Postconditions (what is true on successful completion of the use case - and worth telling about) ..... (5)
- Main Success Scenario (sequence of events for this use case when everything goes right)
  - Stated as User does something, then system does something .... (5)
  - Avoids implementation language .... (3)
  - First step is the trigger event - what causes this use case to start? .... (2)
  - Avoids conditional branches or exceptional conditions .... (5)
- Extensions or Alternate Flows (keyed to step where this occurs in Main Scenario)
  - Number matches step in Main scenario where this exception or alternative happens .... (5)
  - Identifies exceptional condition or alternative .... (5)
  - Contains steps to follow if that condition happens .... (5)

**Comment by z3t1** [comment]
This is a sample use case copied from his slides.
![image](https://cloud.githubusercontent.com/assets/5484110/7886233/b061d15c-05f6-11e5-8bbb-1dd5be9b8803.png)

![image](https://cloud.githubusercontent.com/assets/5484110/7886253/c8e876c2-05f6-11e5-9f07-f92085ece4e2.png)

![image](https://cloud.githubusercontent.com/assets/5484110/7886259/d0917ba8-05f6-11e5-8630-ab0ce76a1822.png)

**Comment by z3t1** [comment]
1. Login User
2. Logout User
3. Register User
4. Edit Profile
5. Search Movies
6. Rate Movie
7. Get Recommendations
8. Get New Releases
9. Get Top Rentals
10. Filter Ratings
11. Activate Admin Mode
12. Modify Account Status (i.e. ban/unban/unlock)
13. List Accounts
