### ISSUE TITLE
Login User

### ISSUE THREAD

**Issue by tyang82** [cs2340-group3/moviebuzz#4]
Use Case 1: User Login
Primary Actor: The User
Stakeholders and Interest:
- User: Wants fast, accurate access their account using the correct username and password without errors with the exception of wrong username or password. Wants be lead to a page where they can create a new account by entering their personal information, such as name, desired username, email, etc., if the user is new.
- System: Wants to match and give the User access to the correct account through their username and password. 
- Preconditions: The User has an account
- Postconditions: The System is able to match the User to his or her correct account, and the User is able to access his/her account using the correct password and username without any errors. 
- Main Success Scenario:
  1. User arrives at the login page by clicking on the login button on the main page.
  2. The User enters his/her username and password on the login page.
  3. The System identifies the username and password of the User and leads the User to his/her account.
- Extensions/Exceptions:
  
  (iii.) Invalid Identifier and/or Password:
    --(i.) System signals error and rejects entry
  **At any time if the System fail to log the User into his/her account
  --(i.) Login page will reload

**Comment by vergenzt** [comment]
![20150529_114802](https://cloud.githubusercontent.com/assets/1725615/7886545/c599b646-05f8-11e5-8b9c-cf5b92c90869.jpg)
