### ISSUE TITLE
Use npm package `email-validator` instead of regex literal

### ISSUE THREAD

**Issue by vergenzt** [cs2340-group3/moviebuzz#49]
https://github.com/cs2340-group3/moviebuzz/blob/master/routes/auth.js#L60

**Comment by z3t1** [comment]
Currently we are using `input type=email` to do front-end validation. According [W3C's standard](http://www.w3.org/TR/html-markup/input.email.html), it's equivalent of <div>/^[a-zA-Z0-9.!#$%&’_+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:.[a-zA-Z0-9-]+)_$/</div>.

But the [email-validator](https://github.com/Sembiance/email-validator/blob/master/index.js) uses <div>/^[-!#$%&'*+\/0-9=?A-Z^_a-z{|}~](.?[-!#$%&'*+/0-9=?A-Z^_a-z`{|}~])_@[a-zA-Z0-9](-?[a-zA-Z0-9])_(.[a-zA-Z](-?[a-zA-Z0-9])*)+$/ </div>

**Comment by z3t1** [comment]
@vergenzt Markdown messes up the regex. Go to the link and see. I am not good at reading regex. If you are sure they are equivalent. We can use the package. Otherwise, I'll copy paste from W3C.

**Comment by z3t1** [comment]
The W3C one somehow doesn't work with JS.

**Comment by z3t1** [comment]
[type=email](http://www.wufoo.com/html5/types/1-email.html) is not a good solution. It just tests the presense of an @ sign

**Comment by z3t1** [comment]
Ok. I solved this by changing the frontend validation regex to the mail-validator one.
