### ISSUE TITLE
Logout User

### ISSUE THREAD

**Issue by kcaras** [cs2340-group3/moviebuzz#5]
Use Case: Log out User

Primary Actor: User

Stakeholders and Interests/Goals:
           • User: desires to exit out of his account so that no one can use it under his name.

Preconditions: User logged into his account successfully.

Post conditions: User is successfully logged out of his account and to get back into it. the user would have to log in again on the log in screen.

Main Success Scenario:
           1. User clicks the “Log out” button on the screen.
           2. System logs the user out and ends their session.
           3. System presents a message that the user is successfully logged out of their account.
           4. System returns to the main Log in/Register page.

Extensions/ Exceptions
           a. at any time System loses connection with the internet
                    1. System logs the user out of his or her account and ends the session.
           b. at any time System fails
                    1. System logs all users out and ends their sessions.

Frequency of Occurrence: Could be nearly continuous if many people desire to log out of the application at the same time.

**Comment by vergenzt** [comment]
See [comment on #4](https://github.com/cs2340-group3/moviebuzz/issues/4#issuecomment-106854184) for mockup

**Comment by kcaras** [comment]
Use Case: Log out User

Primary Actor: User 

Stakeholders and Interests/Goals:
             •    User: desires to exit out of his account so that no one can use it under his name. 

Preconditions: User logged into his account successfully. 

Post conditions: User is successfully logged out of his account and to get back into it. the user would have to log in again on the log in screen. 

Main Success Scenario: 
           1.   User clicks the “Log out” button on the screen.
           2.   System logs the user out and ends their session. 
           3.   System presents a message that the user is successfully logged out of their account. 
           4.   System returns to the main Log in/Register page.
Extensions/ Exceptions 
           a.   _at any time_ System loses connection with the internet 
                    1.  System logs the user out of his or her account and ends the session. 
           b.   _at any time_ System fails
                    1.  System logs all users out and ends their sessions. 

Frequency of Occurrence: Could be nearly continuous if many people desire to log out of the application at the same time.
