### ISSUE TITLE
Show admin dashboard

### ISSUE THREAD

**Issue by vergenzt** [cs2340-group3/moviebuzz#6]
- **Primary Actor**
  - User with admin privileges ("admin")
- **Stakeholders and Interests/Goals**
  - Admins want an easy way to manage user accounts.
  - Users want their accounts to be able to be unlocked.
- **Preconditions**
  - Admin is authenticated.
- **Postconditions**
  - Admin sees a list of user accounts, with modification options.
- **Extensions / Exceptions**: None
- **Frequency of Occurrence**: Frequent.
### Main Success Scenario
1. User with admin privileges is authenticated on any page of the site.
2. User clicks "Admin Dashboard" link on the navbar (only visible to admins).
3. User is directed to the admin dashboard.

**Comment by z3t1** [comment]
To make a user admin, go to `mongo` and `db.users.update({ username: "user" }, { $set: { is_admin: true } })`

**Comment by z3t1** [comment]
#88
