### ISSUE TITLE
Register user

### ISSUE THREAD

**Issue by egraba3** [cs2340-group3/moviebuzz#7]
Use Cases for user registration:

Primary Actor: User

Stakeholders and Interests:
    -User: Wants fast and easy registration with minimal information necessary
    -WebMaster: Wants secure and accurate registration that properly maintains user database

Preconditions: User is on website and has selected "register" option

Postconditions: User information is properly validated and stored in database, user has
access to a functioning account that will pass login validation

Main Success Scenario:
-User arrives at website login page
-User Clicks "Create account" link
-User is taken to a page with text-fields that they can fill their information into
-User presses "submit"
-Information is validated
-Information is stored in database
-User has username and password that link to a functional account
-User is logged in and taken to home page

Extensions / Exceptions:

```
-User enters invalid data in any field:
    -re-load registration page with all text fields cleared
    -Display error message

-User submits page without filling out one or more required fields
    -re-load registration page with all text fields cleared
    -Display error message
```

**Comment by vergenzt** [comment]
See [comment on #4](https://github.com/cs2340-group3/moviebuzz/issues/4#issuecomment-106854184) for mockup

**Comment by vergenzt** [comment]
Implemented and merged
