### ISSUE TITLE
Error message for first time login failure.

### ISSUE THREAD

**Issue by z3t1** [cs2340-group3/moviebuzz#70]
![11541677_460981690738192_442337642_o](https://cloud.githubusercontent.com/assets/5484110/8389018/e807eea0-1c37-11e5-8ca7-b1344add6507.jpg)

**Comment by vergenzt** [comment]
Will be fixed by saintedlama/passport-local-mongoose#90. I'll update `package.json` and close once that's merged.

**Comment by vergenzt** [comment]
Fixed
