### ISSUE TITLE
Method Contract

### ISSUE THREAD

**Issue by z3t1** [cs2340-group3/moviebuzz#94]
@vergenzt @kcaras6 @tyang82 

Example from Book Chapter 11:

<img width="581" alt="screen shot 2015-07-06 at 2 43 28 pm" src="https://cloud.githubusercontent.com/assets/5484110/8530187/76bd3f80-23ed-11e5-9be3-0f06342f397e.png">

<img width="1125" alt="screen shot 2015-07-06 at 2 48 32 pm" src="https://cloud.githubusercontent.com/assets/5484110/8530288/1b17b088-23ee-11e5-913e-2fbbda9f225c.png">

**Comment by z3t1** [comment]
- Operation: [`login(req, res)`](https://github.com/cs2340-group3/moviebuzz/blob/master/api/auth.js#L9-L34)
- Cross references: Use case: user login
- Preconditions: The end-user submits his username and password to the server
- Postconditions: 
  1. If the username and password is correct, a session should be created for the user. (instance creation) This indicates the authentication succeeds.
  2. If the password is incorrect, increment its login failure counter. (attribute modification)
  3. If the failure counter reaches 3, lock the user. (attribute modification)

**Comment by tyang82** [comment]
- Operation: register(req, res, next)
- Cross References: Use Case: Register User
- Preconditions: User enters an alphanumeric username, a valid email address, and a password that is at least 6 characters.
- Postconditions:
  1. If the user enters valid username, email address, and password that is at least 6 characters, a new instance of User is created with the entered username, email, and password. (instance creation) Authentication succeeds.
  2. If user does not enter any one of the following: username, email address, or password, return warning to the user. 
  3. If user enters a non- alphanumeric username, invalid or pre-existing email address, or a password that has less than 6 characters, return and display warning to user.

**Comment by kcaras** [comment]
Operation: updateProfile()
Cross Reference: Use Cases: Update Profile

Preconditions:

```
User has registered successfully.
User is logged in successfully.
```

Postconditions: 

```
If req.body is false the system notifies, invalid input.
If user tries to update an invalid field, the system notifies, invalid input.
If the input is valid the updated fields are stored in updatedData (instance creation) and the current instance of User’s UserSchema is changed to updatedData (attribute modification)
```

**Comment by egraba3** [comment]
Operation: rateMovie(req, res, next)
Cross Reference: Use Cases: rate movie

Preconditions:
  i. User is logged in successfully
  ii. User has entered valid data into the input fields

Postconditions:
  i. User's rating data is properly piped from front end into database
 ii.  User's rating is accessible to other logged in users of the same major

**Comment by z3t1** [comment]
@vergenzt

**Comment by vergenzt** [comment]
Operation: searchMovies(req, res, next)
Cross Reference: Use Cases: search movies

Preconditions:
i. User is logged in with a valid authorization token.

Postconditions:
i. RottenTomatoes's search results have been rendered to the response.
